import { Asignatura } from './asignatura';

export const Horario: { [dia: string]: Asignatura[] } = {
    L: [
      {
        nombre: 'CALIDAD DE SOFTWARE',
        sala: 'SALA E305 LAB. TELECO - INFORMATICA (36)',
        horaInicio: '10:41',
        horaTermino: '11:20',
        seccion: 'CSY4111-003D',
        profesor: 'GERARDO ENRIQUE GALAN CRUZ',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'CALIDAD DE SOFTWARE',
        sala: 'SALA E305 LAB. TELECO - INFORMATICA (36)',
        horaInicio: '11:31',
        horaTermino: '12:10',
        seccion: 'CSY4111-003D',
        profesor: 'GERARDO ENRIQUE GALAN CRUZ',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'PROGRAMACIÓN DE APLICACIONES MÓVILES',
        sala: 'SALA E307 LAB. REDES - INFORMATICA I (30)',
        horaInicio: '12:11',
        horaTermino: '12:50',
        seccion: 'PGY4121-003D',
        profesor: 'ALEJANDRO SEBASTIAN SEPULVEDA MONTERO',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'PROGRAMACIÓN DE APLICACIONES MÓVILES',
        sala: 'SALA E307 LAB. REDES - INFORMATICA I (30)',
        horaInicio: '13:01',
        horaTermino: '14:20',
        seccion: 'PGY4121-003D',
        profesor: 'ALEJANDRO SEBASTIAN SEPULVEDA MONTERO',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'CALIDAD DE SOFTWARE',
        sala: 'SALA E305 LAB. TELECO - INFORMATICA (36)',
        horaInicio: '11:31',
        horaTermino: '12:10',
        seccion: 'CSY4111-003D',
        profesor: 'GERARDO ENRIQUE GALAN CRUZ',
        sede: 'CONCEPCIÓN',
      }
    ],
    M: [
      {
        nombre: 'PROGRAMACIÓN DE APLICACIONES MÓVILES',
        sala: 'SALA E305 LAB. TELECO - INFORMATICA (36)',
        horaInicio: '08:31',
        horaTermino: '09:50',
        seccion: 'PGY4121-003D',
        profesor: 'ALEJANDRO SEBASTIAN SEPULVEDA MONTERO',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'INGLÉS INTERMEDIO',
        sala: 'SALA H605 SALA DE INGLÉS (25)',
        horaInicio: '10:01',
        horaTermino: '11:20',
        seccion: 'INI5111-009D',
        profesor: 'MARISOL OMAIRA OSORIO RIVERA',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'INGLÉS INTERMEDIO',
        sala: 'SALA H605 SALA DE INGLÉS (25)',
        horaInicio: '10:01',
        horaTermino: '11:20',
        seccion: 'INI5111-009D',
        profesor: 'MARISOL OMAIRA OSORIO RIVERA',
        sede: 'CONCEPCIÓN',
      },
      {
        nombre: 'ESTADÍSTICA DESCRIPTIVA',
        sala: 'SALA H614 SALA DE PROYECTO (30)',
        horaInicio: '13:01',
        horaTermino: '14:20',
        seccion: 'MAT4140-003D',
        profesor: 'BRAULIO ANTONIO FERNANDEZ CONTRERAS',
        sede: 'CONCEPCIÓN',
      }
    ],
    X: [
        {
        nombre: 'ARQUITECTURA',
        sala: 'SALA E308 LAB. REDES - INFORMATICA I (30)',
        horaInicio: '08:31',
        horaTermino: '09:50',
        seccion: 'ASY4131-003D',
        profesor: 'JAZNA PATRICIA MEZA HIDALGO',
        sede: 'CONCEPCIÓN',
        },
        {
        nombre: 'INGLÉS INTERMEDIO',
        sala: 'SALA H605 SALA DE INGLÉS (25)',
        horaInicio: '10:01',
        horaTermino: '11:20',
        seccion: 'INI5111-009D',
        profesor: 'MARISOL OMAIRA OSORIO RIVERA',
        sede: 'CONCEPCIÓN',
        },
        {
        nombre: 'INGLÉS INTERMEDIO',
        sala: 'SALA H605 SALA DE INGLÉS (25)',
        horaInicio: '11:31',
        horaTermino: '12:50',
        seccion: 'INI5111-009D',
        profesor: 'MARISOL OMAIRA OSORIO RIVERA',
        sede: 'CONCEPCIÓN',
        },
        {
        nombre: 'ARQUITECTURA',
        sala: 'SALA E308 LAB. REDES - INFORMATICA I (30)',
        horaInicio: '12:11',
        horaTermino: '12:50',
        seccion: 'ASY4131-003D',
        profesor: 'JAZNA PATRICIA MEZA HIDALGO',
        sede: 'CONCEPCIÓN',
        },
        {
        nombre: 'ARQUITECTURA',
        sala: 'SALA E308 LAB. REDES - INFORMATICA I (30)',
        horaInicio: '12:11',
        horaTermino: '12:50',
        seccion: 'ASY4131-003D',
        profesor: 'JAZNA PATRICIA MEZA HIDALGO',
        sede: 'CONCEPCIÓN',
        }
      ],
      J: [
        {
          nombre: 'ÉTICA PARA EL TRABAJO',
          sala: 'SALA E509 SALA TEORICA (45)',
          horaInicio: '08:31',
          horaTermino: '09:50',
          seccion: 'EAY4470-003D',
          profesor: 'JUAN CARLOS BURGOS ULLOA',
          sede: 'CONCEPCIÓN',
        },
        {
          nombre: 'INGLÉS INTERMEDIO',
          sala: 'SALA H605 SALA DE INGLÉS (25)',
          horaInicio: '10:01',
          horaTermino: '11:20',
          seccion: 'INI5111-009D',
          profesor: 'MARISOL OMAIRA OSORIO RIVERA',
          sede: 'CONCEPCIÓN',
        },
        {
          nombre: 'ESTADÍSTICA DESCRIPTIVA',
          sala: 'SALA E307 LAB. REDES - INFORMATICA I (30)',
          horaInicio: '11:31',
          horaTermino: '12:50',
          seccion: 'MAT4140-003D',
          profesor: 'BRAULIO ANTONIO FERNANDEZ CONTRERAS',
          sede: 'CONCEPCIÓN',
        }
      ],
  };
  